### ISSUE TITLE
Incompatible with `Rocket` survivor

### ISSUE THREAD

**Issue by Moffein** [6thmoon/UnlockMomentum#2]
When rocket jumping with Rocket while using this mod, his velocity will start scaling super fast. My guess is that the momentum conservation code tied to Rocket's Rocket Jump buff is stacking with the code in this mod somehow. No nullrefs in console or anything like that.
Not sure if this is something that needs to be implemented on my end or this mod's end, but here's the code for it if you would like to take a look.
https://github.com/Moffein/RocketSurvivor/blob/master/HenryMod/Buffs.cs

**Comment by 6thmoon** [comment]
Hey, apologies for the delayed response. I am out of town for the next few weeks, thus unable to verify this - but the interaction appears to be fairly straightforward. It is interesting to see the similarities between the two implementations.

Both of these plugins increase the length of the target vector in order to retain a degree of control at high velocities. However, since I use the character's movement speed in that calculation, it does not take into account your changes. The solution would to use the magnitude instead on my end rather than assume that these would be proportional.

**Comment by 6thmoon** [comment]
This should be fixed in version [`0.1.6`](https://github.com/6thmoon/UnlockMomentum/blob/v0.1.6/Plugin.cs#L82), but let me know if there are still any issues.
